name: Release Drafter

on:
  workflow_call:
    inputs:
      config-name:
        required: false
        type: string
    secrets:
      token:
        description: 'The GitHub Token'
        required: true

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          config-name: ${{  inputs.config-name || '.github/release-drafter.yml' }}
